package moe.foxie.sol.acmusic

import android.util.Log

val WOLF_FENCE = "WF"

fun wolfFence(value: String) = Log.d(WOLF_FENCE,value)

const val DOMAIN_PREFIX = "moe.foxie.sol.acmusic."

const val MUSIC_SERVICE_ONLINE = DOMAIN_PREFIX + "ACTION_MUSIC_SERVICE_ONLINE"
const val MUSIC_SERVICE_OFFLINE = DOMAIN_PREFIX + "ACTION_MUSIC_SERVICE_OFFLINE"
const val MUSIC_SERVICE = DOMAIN_PREFIX + "ACTION_MUSIC_SERVICE"
const val MUSIC_SERVICE_PLAY_PAUSE = DOMAIN_PREFIX + "ACTION_MUSIC_PLAY_PAUSE"

const val SERVICE_NOTIFICATION_CHANNEL = DOMAIN_PREFIX + "SERVICE_NOTIFICATION_CHANNEL"
const val APP_ACTIVITY_SETTINGS = DOMAIN_PREFIX + "APP_ACTIVITY_SETTINGS"