package moe.foxie.sol.acmusic

val SUNNY = ACWeather.SUNNY
val RAINY = ACWeather.RAINY
val SNOWY = ACWeather.SNOWY

//Tracks for Animal Crossing: New Leaf
val acnlTracks = hashMapOf(
    Pair(0,SUNNY) to R.raw.nl12am,
    Pair(1,SUNNY) to R.raw.nl1am,
    Pair(2,SUNNY) to R.raw.nl2am,
    Pair(3,SUNNY) to R.raw.nl3am,
    Pair(4,SUNNY) to R.raw.nl4am,
    Pair(5,SUNNY) to R.raw.nl5am,
    Pair(6,SUNNY) to R.raw.nl6am,
    Pair(7,SUNNY) to R.raw.nl7am,
    Pair(8,SUNNY) to R.raw.nl8am,
    Pair(9,SUNNY) to R.raw.nl9am,
    Pair(10,SUNNY) to R.raw.nl10am,
    Pair(11,SUNNY) to R.raw.nl11am,
    Pair(12,SUNNY) to R.raw.nl12pm,
    Pair(13,SUNNY) to R.raw.nl1pm,
    Pair(14,SUNNY) to R.raw.nl2pm,
    Pair(15,SUNNY) to R.raw.nl3pm,
    Pair(16,SUNNY) to R.raw.nl4pm,
    Pair(17,SUNNY) to R.raw.nl5pm,
    Pair(18,SUNNY) to R.raw.nl6pm,
    Pair(19,SUNNY) to R.raw.nl7pm,
    Pair(20,SUNNY) to R.raw.nl8pm,
    Pair(21,SUNNY) to R.raw.nl9pm,
    Pair(22,SUNNY) to R.raw.nl10pm,
    Pair(23,SUNNY) to R.raw.nl11pm,

    Pair(0,RAINY) to R.raw.nlr12am,
    Pair(1,RAINY) to R.raw.nlr1am,
    Pair(2,RAINY) to R.raw.nlr2am,
    Pair(3,RAINY) to R.raw.nlr3am,
    Pair(4,RAINY) to R.raw.nlr4am,
    Pair(5,RAINY) to R.raw.nlr5am,
    Pair(6,RAINY) to R.raw.nlr6am,
    Pair(7,RAINY) to R.raw.nlr7am,
    Pair(8,RAINY) to R.raw.nlr8am,
    Pair(9,RAINY) to R.raw.nlr9am,
    Pair(10,RAINY) to R.raw.nlr10am,
    Pair(11,RAINY) to R.raw.nlr11am,
    Pair(12,RAINY) to R.raw.nlr12pm,
    Pair(13,RAINY) to R.raw.nlr1pm,
    Pair(14,RAINY) to R.raw.nlr2pm,
    Pair(15,RAINY) to R.raw.nlr3pm,
    Pair(16,RAINY) to R.raw.nlr4pm,
    Pair(17,RAINY) to R.raw.nlr5pm,
    Pair(18,RAINY) to R.raw.nlr6pm,
    Pair(19,RAINY) to R.raw.nlr7pm,
    Pair(20,RAINY) to R.raw.nlr8pm,
    Pair(21,RAINY) to R.raw.nlr9pm,
    Pair(22,RAINY) to R.raw.nlr10pm,
    Pair(23,RAINY) to R.raw.nlr11pm,

    Pair(0,SNOWY) to R.raw.nls12am,
    Pair(1,SNOWY) to R.raw.nls1am,
    Pair(2,SNOWY) to R.raw.nls2am,
    Pair(3,SNOWY) to R.raw.nls3am,
    Pair(4,SNOWY) to R.raw.nls4am,
    Pair(5,SNOWY) to R.raw.nls5am,
    Pair(6,SNOWY) to R.raw.nls6am,
    Pair(7,SNOWY) to R.raw.nls7am,
    Pair(8,SNOWY) to R.raw.nls8am,
    Pair(9,SNOWY) to R.raw.nls9am,
    Pair(10,SNOWY) to R.raw.nls10am,
    Pair(11,SNOWY) to R.raw.nls11am,
    Pair(12,SNOWY) to R.raw.nls12pm,
    Pair(13,SNOWY) to R.raw.nls1pm,
    Pair(14,SNOWY) to R.raw.nls2pm,
    Pair(15,SNOWY) to R.raw.nls3pm,
    Pair(16,SNOWY) to R.raw.nls4pm,
    Pair(17,SNOWY) to R.raw.nls5pm,
    Pair(18,SNOWY) to R.raw.nls6pm,
    Pair(19,SNOWY) to R.raw.nls7pm,
    Pair(20,SNOWY) to R.raw.nls8pm,
    Pair(21,SNOWY) to R.raw.nls9pm,
    Pair(22,SNOWY) to R.raw.nls10pm,
    Pair(23,SNOWY) to R.raw.nls11pm
)

val acnlTrackNames = hashMapOf(
    Pair(0,SUNNY) to "12AM (Sunny)",
    Pair(1,SUNNY) to "1AM (Sunny)",
    Pair(2,SUNNY) to "2AM (Sunny)",
    Pair(3,SUNNY) to "3AM (Sunny)",
    Pair(4,SUNNY) to "4AM (Sunny)",
    Pair(5,SUNNY) to "5AM (Sunny)",
    Pair(6,SUNNY) to "6AM (Sunny)",
    Pair(7,SUNNY) to "7AM (Sunny)",
    Pair(8,SUNNY) to "8AM (Sunny)",
    Pair(9,SUNNY) to "9AM (Sunny)",
    Pair(10,SUNNY) to "10AM (Sunny)",
    Pair(11,SUNNY) to "11AM (Sunny)",
    Pair(12,SUNNY) to "12PM (Sunny)",
    Pair(13,SUNNY) to "1PM (Sunny)",
    Pair(14,SUNNY) to "2PM (Sunny)",
    Pair(15,SUNNY) to "3PM (Sunny)",
    Pair(16,SUNNY) to "4PM (Sunny)",
    Pair(17,SUNNY) to "5PM (Sunny)",
    Pair(18,SUNNY) to "6PM (Sunny)",
    Pair(19,SUNNY) to "7PM (Sunny)",
    Pair(20,SUNNY) to "8PM (Sunny)",
    Pair(21,SUNNY) to "9PM (Sunny)",
    Pair(22,SUNNY) to "10PM (Sunny)",
    Pair(23,SUNNY) to "11PM (Sunny)",
    Pair(0,RAINY) to "12AM (Rainy)",
    Pair(1,RAINY) to "1AM (Rainy)",
    Pair(2,RAINY) to "2AM (Rainy)",
    Pair(3,RAINY) to "3AM (Rainy)",
    Pair(4,RAINY) to "4AM (Rainy)",
    Pair(5,RAINY) to "5AM (Rainy)",
    Pair(6,RAINY) to "6AM (Rainy)",
    Pair(7,RAINY) to "7AM (Rainy)",
    Pair(8,RAINY) to "8AM (Rainy)",
    Pair(9,RAINY) to "9AM (Rainy)",
    Pair(10,RAINY) to "10AM (Rainy)",
    Pair(11,RAINY) to "11AM (Rainy)",
    Pair(12,RAINY) to "12PM (Rainy)",
    Pair(13,RAINY) to "1PM (Rainy)",
    Pair(14,RAINY) to "2PM (Rainy)",
    Pair(15,RAINY) to "3PM (Rainy)",
    Pair(16,RAINY) to "4PM (Rainy)",
    Pair(17,RAINY) to "5PM (Rainy)",
    Pair(18,RAINY) to "6PM (Rainy)",
    Pair(19,RAINY) to "7PM (Rainy)",
    Pair(20,RAINY) to "8PM (Rainy)",
    Pair(21,RAINY) to "9PM (Rainy)",
    Pair(22,RAINY) to "10PM (Rainy)",
    Pair(23,RAINY) to "11PM (Rainy)",
    Pair(0,SNOWY) to "12AM (Snowy)",
    Pair(1,SNOWY) to "1AM (Snowy)",
    Pair(2,SNOWY) to "2AM (Snowy)",
    Pair(3,SNOWY) to "3AM (Snowy)",
    Pair(4,SNOWY) to "4AM (Snowy)",
    Pair(5,SNOWY) to "5AM (Snowy)",
    Pair(6,SNOWY) to "6AM (Snowy)",
    Pair(7,SNOWY) to "7AM (Snowy)",
    Pair(8,SNOWY) to "8AM (Snowy)",
    Pair(9,SNOWY) to "9AM (Snowy)",
    Pair(10,SNOWY) to "10AM (Snowy)",
    Pair(11,SNOWY) to "11AM (Snowy)",
    Pair(12,SNOWY) to "12PM (Snowy)",
    Pair(13,SNOWY) to "1PM (Snowy)",
    Pair(14,SNOWY) to "2PM (Snowy)",
    Pair(15,SNOWY) to "3PM (Snowy)",
    Pair(16,SNOWY) to "4PM (Snowy)",
    Pair(17,SNOWY) to "5PM (Snowy)",
    Pair(18,SNOWY) to "6PM (Snowy)",
    Pair(19,SNOWY) to "7PM (Snowy)",
    Pair(20,SNOWY) to "8PM (Snowy)",
    Pair(21,SNOWY) to "9PM (Snowy)",
    Pair(22,SNOWY) to "10PM (Snowy)",
    Pair(23,SNOWY) to "11PM (Snowy)"
)

// todo: add global constant for Totaka's Song, for playing when an error occurs
