package moe.foxie.sol.acmusic

val SUNNY = ACWeather.SUNNY
val RAINY = ACWeather.RAINY
val SNOWY = ACWeather.SNOWY


data class TrackID(val hour: Int, val weather: ACWeather)
/** like trackID but with extra diagnostic information */
data class TrackInfo(val hour: Int, val forecast: WeatherManager.Forecast) {
    val trackID = TrackID(hour, forecast.weather)
}

//Tracks for Animal Crossing: New Leaf
val acnlTracks = hashMapOf(
    TrackID(0,SUNNY) to R.raw.nl12am,
    TrackID(1,SUNNY) to R.raw.nl1am,
    TrackID(2,SUNNY) to R.raw.nl2am,
    TrackID(3,SUNNY) to R.raw.nl3am,
    TrackID(4,SUNNY) to R.raw.nl4am,
    TrackID(5,SUNNY) to R.raw.nl5am,
    TrackID(6,SUNNY) to R.raw.nl6am,
    TrackID(7,SUNNY) to R.raw.nl7am,
    TrackID(8,SUNNY) to R.raw.nl8am,
    TrackID(9,SUNNY) to R.raw.nl9am,
    TrackID(10,SUNNY) to R.raw.nl10am,
    TrackID(11,SUNNY) to R.raw.nl11am,
    TrackID(12,SUNNY) to R.raw.nl12pm,
    TrackID(13,SUNNY) to R.raw.nl1pm,
    TrackID(14,SUNNY) to R.raw.nl2pm,
    TrackID(15,SUNNY) to R.raw.nl3pm,
    TrackID(16,SUNNY) to R.raw.nl4pm,
    TrackID(17,SUNNY) to R.raw.nl5pm,
    TrackID(18,SUNNY) to R.raw.nl6pm,
    TrackID(19,SUNNY) to R.raw.nl7pm,
    TrackID(20,SUNNY) to R.raw.nl8pm,
    TrackID(21,SUNNY) to R.raw.nl9pm,
    TrackID(22,SUNNY) to R.raw.nl10pm,
    TrackID(23,SUNNY) to R.raw.nl11pm,

    TrackID(0,RAINY) to R.raw.nlr12am,
    TrackID(1,RAINY) to R.raw.nlr1am,
    TrackID(2,RAINY) to R.raw.nlr2am,
    TrackID(3,RAINY) to R.raw.nlr3am,
    TrackID(4,RAINY) to R.raw.nlr4am,
    TrackID(5,RAINY) to R.raw.nlr5am,
    TrackID(6,RAINY) to R.raw.nlr6am,
    TrackID(7,RAINY) to R.raw.nlr7am,
    TrackID(8,RAINY) to R.raw.nlr8am,
    TrackID(9,RAINY) to R.raw.nlr9am,
    TrackID(10,RAINY) to R.raw.nlr10am,
    TrackID(11,RAINY) to R.raw.nlr11am,
    TrackID(12,RAINY) to R.raw.nlr12pm,
    TrackID(13,RAINY) to R.raw.nlr1pm,
    TrackID(14,RAINY) to R.raw.nlr2pm,
    TrackID(15,RAINY) to R.raw.nlr3pm,
    TrackID(16,RAINY) to R.raw.nlr4pm,
    TrackID(17,RAINY) to R.raw.nlr5pm,
    TrackID(18,RAINY) to R.raw.nlr6pm,
    TrackID(19,RAINY) to R.raw.nlr7pm,
    TrackID(20,RAINY) to R.raw.nlr8pm,
    TrackID(21,RAINY) to R.raw.nlr9pm,
    TrackID(22,RAINY) to R.raw.nlr10pm,
    TrackID(23,RAINY) to R.raw.nlr11pm,

    TrackID(0,SNOWY) to R.raw.nls12am,
    TrackID(1,SNOWY) to R.raw.nls1am,
    TrackID(2,SNOWY) to R.raw.nls2am,
    TrackID(3,SNOWY) to R.raw.nls3am,
    TrackID(4,SNOWY) to R.raw.nls4am,
    TrackID(5,SNOWY) to R.raw.nls5am,
    TrackID(6,SNOWY) to R.raw.nls6am,
    TrackID(7,SNOWY) to R.raw.nls7am,
    TrackID(8,SNOWY) to R.raw.nls8am,
    TrackID(9,SNOWY) to R.raw.nls9am,
    TrackID(10,SNOWY) to R.raw.nls10am,
    TrackID(11,SNOWY) to R.raw.nls11am,
    TrackID(12,SNOWY) to R.raw.nls12pm,
    TrackID(13,SNOWY) to R.raw.nls1pm,
    TrackID(14,SNOWY) to R.raw.nls2pm,
    TrackID(15,SNOWY) to R.raw.nls3pm,
    TrackID(16,SNOWY) to R.raw.nls4pm,
    TrackID(17,SNOWY) to R.raw.nls5pm,
    TrackID(18,SNOWY) to R.raw.nls6pm,
    TrackID(19,SNOWY) to R.raw.nls7pm,
    TrackID(20,SNOWY) to R.raw.nls8pm,
    TrackID(21,SNOWY) to R.raw.nls9pm,
    TrackID(22,SNOWY) to R.raw.nls10pm,
    TrackID(23,SNOWY) to R.raw.nls11pm
)

val acwwTracks = hashMapOf(
    TrackID(0,SUNNY) to R.raw.ww12am,
    TrackID(1,SUNNY) to R.raw.ww2am,
    TrackID(2,SUNNY) to R.raw.ww3am,
    TrackID(3,SUNNY) to R.raw.ww4am,
    TrackID(4,SUNNY) to R.raw.ww5am,
    TrackID(5,SUNNY) to R.raw.ww6am,
    TrackID(6,SUNNY) to R.raw.ww7am,
    TrackID(7,SUNNY) to R.raw.ww8am,
    TrackID(8,SUNNY) to R.raw.ww9am,
    TrackID(9,SUNNY) to R.raw.ww10am,
    TrackID(10,SUNNY) to R.raw.ww11am,
    TrackID(11,SUNNY) to R.raw.ww12am,
    TrackID(12,SUNNY) to R.raw.ww12pm,
    TrackID(13,SUNNY) to R.raw.ww1pm,
    TrackID(14,SUNNY) to R.raw.ww2pm,
    TrackID(15,SUNNY) to R.raw.ww3pm,
    TrackID(16,SUNNY) to R.raw.ww4pm,
    TrackID(17,SUNNY) to R.raw.ww5pm,
    TrackID(18,SUNNY) to R.raw.ww6pm,
    TrackID(19,SUNNY) to R.raw.ww7pm,
    TrackID(20,SUNNY) to R.raw.ww8pm,
    TrackID(21,SUNNY) to R.raw.ww9pm,
    TrackID(22,SUNNY) to R.raw.ww10pm,
    TrackID(23,SUNNY) to R.raw.ww11pm,

    TrackID(0,RAINY) to R.raw.wwr12am,
    TrackID(1,RAINY) to R.raw.wwr2am,
    TrackID(2,RAINY) to R.raw.wwr3am,
    TrackID(3,RAINY) to R.raw.wwr4am,
    TrackID(4,RAINY) to R.raw.wwr5am,
    TrackID(5,RAINY) to R.raw.wwr6am,
    TrackID(6,RAINY) to R.raw.wwr7am,
    TrackID(7,RAINY) to R.raw.wwr8am,
    TrackID(8,RAINY) to R.raw.wwr9am,
    TrackID(9,RAINY) to R.raw.wwr10am,
    TrackID(10,RAINY) to R.raw.wwr11am,
    TrackID(11,RAINY) to R.raw.wwr12am,
    TrackID(12,RAINY) to R.raw.wwr12pm,
    TrackID(13,RAINY) to R.raw.wwr1pm,
    TrackID(14,RAINY) to R.raw.wwr2pm,
    TrackID(15,RAINY) to R.raw.wwr3pm,
    TrackID(16,RAINY) to R.raw.wwr4pm,
    TrackID(17,RAINY) to R.raw.wwr5pm,
    TrackID(18,RAINY) to R.raw.wwr6pm,
    TrackID(19,RAINY) to R.raw.wwr7pm,
    TrackID(20,RAINY) to R.raw.wwr8pm,
    TrackID(21,RAINY) to R.raw.wwr9pm,
    TrackID(22,RAINY) to R.raw.wwr10pm,
    TrackID(23,RAINY) to R.raw.wwr11pm,


    TrackID(0,SNOWY) to R.raw.wws12am,
    TrackID(1,SNOWY) to R.raw.wws2am,
    TrackID(2,SNOWY) to R.raw.wws3am,
    TrackID(3,SNOWY) to R.raw.wws4am,
    TrackID(4,SNOWY) to R.raw.wws5am,
    TrackID(5,SNOWY) to R.raw.wws6am,
    TrackID(6,SNOWY) to R.raw.wws7am,
    TrackID(7,SNOWY) to R.raw.wws8am,
    TrackID(8,SNOWY) to R.raw.wws9am,
    TrackID(9,SNOWY) to R.raw.wws10am,
    TrackID(10,SNOWY) to R.raw.wws11am,
    TrackID(11,SNOWY) to R.raw.wws12am,
    TrackID(12,SNOWY) to R.raw.wws12pm,
    TrackID(13,SNOWY) to R.raw.wws1pm,
    TrackID(14,SNOWY) to R.raw.wws2pm,
    TrackID(15,SNOWY) to R.raw.wws3pm,
    TrackID(16,SNOWY) to R.raw.wws4pm,
    TrackID(17,SNOWY) to R.raw.wws5pm,
    TrackID(18,SNOWY) to R.raw.wws6pm,
    TrackID(19,SNOWY) to R.raw.wws7pm,
    TrackID(20,SNOWY) to R.raw.wws8pm,
    TrackID(21,SNOWY) to R.raw.wws9pm,
    TrackID(22,SNOWY) to R.raw.wws10pm,
    TrackID(23,SNOWY) to R.raw.wws11pm
)

val afTracks = hashMapOf(
    TrackID(0,SUNNY) to R.raw.af12am,
    TrackID(1,SUNNY) to R.raw.af2am,
    TrackID(2,SUNNY) to R.raw.af3am,
    TrackID(3,SUNNY) to R.raw.af4am,
    TrackID(4,SUNNY) to R.raw.af5am,
    TrackID(5,SUNNY) to R.raw.af6am,
    TrackID(6,SUNNY) to R.raw.af7am,
    TrackID(7,SUNNY) to R.raw.af8am,
    TrackID(8,SUNNY) to R.raw.af9am,
    TrackID(9,SUNNY) to R.raw.af10am,
    TrackID(10,SUNNY) to R.raw.af11am,
    TrackID(11,SUNNY) to R.raw.af12am,
    TrackID(12,SUNNY) to R.raw.af12pm,
    TrackID(13,SUNNY) to R.raw.af1pm,
    TrackID(14,SUNNY) to R.raw.af2pm,
    TrackID(15,SUNNY) to R.raw.af3pm,
    TrackID(16,SUNNY) to R.raw.af4pm,
    TrackID(17,SUNNY) to R.raw.af5pm,
    TrackID(18,SUNNY) to R.raw.af6pm,
    TrackID(19,SUNNY) to R.raw.af7pm,
    TrackID(20,SUNNY) to R.raw.af8pm,
    TrackID(21,SUNNY) to R.raw.af9pm,
    TrackID(22,SUNNY) to R.raw.af10pm,
    TrackID(23,SUNNY) to R.raw.af11pm,

    TrackID(0,RAINY) to R.raw.af12am,
    TrackID(1,RAINY) to R.raw.af2am,
    TrackID(2,RAINY) to R.raw.af3am,
    TrackID(3,RAINY) to R.raw.af4am,
    TrackID(4,RAINY) to R.raw.af5am,
    TrackID(5,RAINY) to R.raw.af6am,
    TrackID(6,RAINY) to R.raw.af7am,
    TrackID(7,RAINY) to R.raw.af8am,
    TrackID(8,RAINY) to R.raw.af9am,
    TrackID(9,RAINY) to R.raw.af10am,
    TrackID(10,RAINY) to R.raw.af11am,
    TrackID(11,RAINY) to R.raw.af12am,
    TrackID(12,RAINY) to R.raw.af12pm,
    TrackID(13,RAINY) to R.raw.af1pm,
    TrackID(14,RAINY) to R.raw.af2pm,
    TrackID(15,RAINY) to R.raw.af3pm,
    TrackID(16,RAINY) to R.raw.af4pm,
    TrackID(17,RAINY) to R.raw.af5pm,
    TrackID(18,RAINY) to R.raw.af6pm,
    TrackID(19,RAINY) to R.raw.af7pm,
    TrackID(20,RAINY) to R.raw.af8pm,
    TrackID(21,RAINY) to R.raw.af9pm,
    TrackID(22,RAINY) to R.raw.af10pm,
    TrackID(23,RAINY) to R.raw.af11pm,

    TrackID(0,SNOWY) to R.raw.af12am,
    TrackID(1,SNOWY) to R.raw.af2am,
    TrackID(2,SNOWY) to R.raw.af3am,
    TrackID(3,SNOWY) to R.raw.af4am,
    TrackID(4,SNOWY) to R.raw.af5am,
    TrackID(5,SNOWY) to R.raw.af6am,
    TrackID(6,SNOWY) to R.raw.af7am,
    TrackID(7,SNOWY) to R.raw.af8am,
    TrackID(8,SNOWY) to R.raw.af9am,
    TrackID(9,SNOWY) to R.raw.af10am,
    TrackID(10,SNOWY) to R.raw.af11am,
    TrackID(11,SNOWY) to R.raw.af12am,
    TrackID(12,SNOWY) to R.raw.af12pm,
    TrackID(13,SNOWY) to R.raw.af1pm,
    TrackID(14,SNOWY) to R.raw.af2pm,
    TrackID(15,SNOWY) to R.raw.af3pm,
    TrackID(16,SNOWY) to R.raw.af4pm,
    TrackID(17,SNOWY) to R.raw.af5pm,
    TrackID(18,SNOWY) to R.raw.af6pm,
    TrackID(19,SNOWY) to R.raw.af7pm,
    TrackID(20,SNOWY) to R.raw.af8pm,
    TrackID(21,SNOWY) to R.raw.af9pm,
    TrackID(22,SNOWY) to R.raw.af10pm,
    TrackID(23,SNOWY) to R.raw.af11pm
)

val trackNames = hashMapOf(
    TrackID(0,SUNNY) to "12AM (Sunny)",
    TrackID(1,SUNNY) to "1AM (Sunny)",
    TrackID(2,SUNNY) to "2AM (Sunny)",
    TrackID(3,SUNNY) to "3AM (Sunny)",
    TrackID(4,SUNNY) to "4AM (Sunny)",
    TrackID(5,SUNNY) to "5AM (Sunny)",
    TrackID(6,SUNNY) to "6AM (Sunny)",
    TrackID(7,SUNNY) to "7AM (Sunny)",
    TrackID(8,SUNNY) to "8AM (Sunny)",
    TrackID(9,SUNNY) to "9AM (Sunny)",
    TrackID(10,SUNNY) to "10AM (Sunny)",
    TrackID(11,SUNNY) to "11AM (Sunny)",
    TrackID(12,SUNNY) to "12PM (Sunny)",
    TrackID(13,SUNNY) to "1PM (Sunny)",
    TrackID(14,SUNNY) to "2PM (Sunny)",
    TrackID(15,SUNNY) to "3PM (Sunny)",
    TrackID(16,SUNNY) to "4PM (Sunny)",
    TrackID(17,SUNNY) to "5PM (Sunny)",
    TrackID(18,SUNNY) to "6PM (Sunny)",
    TrackID(19,SUNNY) to "7PM (Sunny)",
    TrackID(20,SUNNY) to "8PM (Sunny)",
    TrackID(21,SUNNY) to "9PM (Sunny)",
    TrackID(22,SUNNY) to "10PM (Sunny)",
    TrackID(23,SUNNY) to "11PM (Sunny)",
    TrackID(0,RAINY) to "12AM (Rainy)",
    TrackID(1,RAINY) to "1AM (Rainy)",
    TrackID(2,RAINY) to "2AM (Rainy)",
    TrackID(3,RAINY) to "3AM (Rainy)",
    TrackID(4,RAINY) to "4AM (Rainy)",
    TrackID(5,RAINY) to "5AM (Rainy)",
    TrackID(6,RAINY) to "6AM (Rainy)",
    TrackID(7,RAINY) to "7AM (Rainy)",
    TrackID(8,RAINY) to "8AM (Rainy)",
    TrackID(9,RAINY) to "9AM (Rainy)",
    TrackID(10,RAINY) to "10AM (Rainy)",
    TrackID(11,RAINY) to "11AM (Rainy)",
    TrackID(12,RAINY) to "12PM (Rainy)",
    TrackID(13,RAINY) to "1PM (Rainy)",
    TrackID(14,RAINY) to "2PM (Rainy)",
    TrackID(15,RAINY) to "3PM (Rainy)",
    TrackID(16,RAINY) to "4PM (Rainy)",
    TrackID(17,RAINY) to "5PM (Rainy)",
    TrackID(18,RAINY) to "6PM (Rainy)",
    TrackID(19,RAINY) to "7PM (Rainy)",
    TrackID(20,RAINY) to "8PM (Rainy)",
    TrackID(21,RAINY) to "9PM (Rainy)",
    TrackID(22,RAINY) to "10PM (Rainy)",
    TrackID(23,RAINY) to "11PM (Rainy)",
    TrackID(0,SNOWY) to "12AM (Snowy)",
    TrackID(1,SNOWY) to "1AM (Snowy)",
    TrackID(2,SNOWY) to "2AM (Snowy)",
    TrackID(3,SNOWY) to "3AM (Snowy)",
    TrackID(4,SNOWY) to "4AM (Snowy)",
    TrackID(5,SNOWY) to "5AM (Snowy)",
    TrackID(6,SNOWY) to "6AM (Snowy)",
    TrackID(7,SNOWY) to "7AM (Snowy)",
    TrackID(8,SNOWY) to "8AM (Snowy)",
    TrackID(9,SNOWY) to "9AM (Snowy)",
    TrackID(10,SNOWY) to "10AM (Snowy)",
    TrackID(11,SNOWY) to "11AM (Snowy)",
    TrackID(12,SNOWY) to "12PM (Snowy)",
    TrackID(13,SNOWY) to "1PM (Snowy)",
    TrackID(14,SNOWY) to "2PM (Snowy)",
    TrackID(15,SNOWY) to "3PM (Snowy)",
    TrackID(16,SNOWY) to "4PM (Snowy)",
    TrackID(17,SNOWY) to "5PM (Snowy)",
    TrackID(18,SNOWY) to "6PM (Snowy)",
    TrackID(19,SNOWY) to "7PM (Snowy)",
    TrackID(20,SNOWY) to "8PM (Snowy)",
    TrackID(21,SNOWY) to "9PM (Snowy)",
    TrackID(22,SNOWY) to "10PM (Snowy)",
    TrackID(23,SNOWY) to "11PM (Snowy)"
)

// todo: add global constant for Totaka's Song, for playing when an error occurs
